services:
  db:
    image: mysql:8.0
    container_name: toy-chat-mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: chat_db
      MYSQL_USER: greenpig
      MYSQL_PASSWORD: green759
      TZ: Asia/Seoul

    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci

    volumes:
      - ./db/data:/var/lib/mysql

  redis:
    image: redis:alpine
    container_name: toy-chat-redis
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --requirepass green759 # 비밀번호 설정
    volumes:
      - ./redis/data:/data
    environment:
      TZ: Asia/Seoul