spring:
  application:
    name: toychat

  datasource:
    url: jdbc:mysql://localhost:3306/chat_db?useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: greenpig
    password: green759
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
     hibernate:
       ddl-auto: update
     properties:
       hibernate:
         format_sql: true
         show_sql: true

  data:
    redis:
      host: localhost
      port: 6379
      password: "green759"

# jwt 설정
jwt:
  # HS512 알고리즘을 쓰려면 64byte(512bit) 이상의 긴 문자열이 필요함!
  # 터미널에서 'openssl rand -base64 64' 쳐서 나온 값 쓰면 됨.
  secret: "ov4dLeKlGO4w+nJqW+SLOhn1dfbnKusqlQXU0BsKjkQ4TjGyEdnRC1DMqRcu4ssn8FpzDTgOCqbwghq3doJHvg=="
  # Access Token 만료 시간(30분)
  access-token-validity-in-milliseconds: 1800000
  # Refresh Token 만료 시간(7일)
  refresh-token-validity-in-milliseconds: 604800000


